---
safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /2.3/
basepath:    /2.3
url: http://localhost:4000/
examples: https://github.com/scalatra/scalatra-website-examples/tree/master/2.3/

jetty_version: 9.1.3.v20140225
scalatra_version: 2.3.0
servlet_version: 3.1.0
json4s_version: 3.2.9
swagger_version: 1.2.0
logback_version: 1.1.1
start_script_plugin_version: 0.5.3
start_script_plugin_version_for_sbt_0_13_0: 0.10.0
akka_version: 2.3.4

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
permalink:   date
paginate:    6
paginate_files: 
  - news.html
  - index.html